# Generated by Django 5.2.4 on 2026-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.TextField(verbose_name='歌詞')),
                ('title', models.CharField(max_length=100, verbose_name='曲名（正解）')),
                ('dummy_choice1', models.CharField(max_length=100, verbose_name='ダミー選択肢1')),
                ('dummy_choice2', models.CharField(max_length=100, verbose_name='ダミー選択肢2')),
            ],
        ),
    ]
