# Generated by Django 5.2.4 on 2026-01-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='アルバム名')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='発売日')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名')),
                ('lyrics', models.TextField(verbose_name='歌詞')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='quiz.album', verbose_name='収録アルバム')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
